version: '2'

services:

  broadsea-methods-library:
    image: ohdsi/broadsea-methodslibrary
    ports:
      - "8787:8787"
      - "6311:6311"
    environment: 
      - USER="${RSTUDIO_USER}"
      - PASSWORD="${RSTUDIO_PASSWORD}"  